use std::{
    cell::LazyCell,
    sync::LazyLock,
};

pub const PRODUCTION: bool = true;
pub const BUILD_ID: u32 = 1123;

pub const PORT: u16 = 8080;

pub const FPS: u32 = 25;
pub const MSPT: u64 = 1000 / (FPS as u64);

pub const PLAYER_INVINCIBILITY_TICKS: u32 = 20 * FPS;
// pub const WANTED_SHAPE_COUNT: usize = 500;
// pub const WANTED_SHAPE_COUNT: usize = 100;

pub const MAX_NICKNAME_LENGTH: u32 = 15;
pub const MAX_FINGERPRINT_LENGTH: u32 = 128;
pub const MAX_USER_ID_LENGTH: u32 = 4096;
pub const MAX_MESSAGE_LENGTH: u32 = 75;
pub const MAX_CLAN_NAME_LENGTH: u32 = 12;

pub const MAX_CLANS: u8 = 10;
pub const MESSAGE_EXPIRY: u32 = 5 * FPS;
pub const DISCONNECT_TIMEOUT: u32 = 5 * FPS;
// pub const ARENA_SIZE: f32 = 5000.0;
pub const AI_VIEW: f32 = 800.0;
pub const LEADER_ARROW_VIEW: f32 = 1000.0;

pub const CELL_SIZE: u32 = 8;
pub const FRICTION: f32 = 0.9;

pub const BASE_TANK_RADIUS: f32 = 30.0;

pub const TOKEN_HASHES: [&str; 2] = [
    "[redacted]",    // MODERATOR
    "[redacted]",    // DEVELOPER
];

pub static BLACKLISTED_HEADER_ORDERS: LazyLock<[Vec<&str>; 2]> = LazyLock::new(|| {
    [
        vec![
            "origin",
            "sec-websocket-version",
            "sec-websocket-key",
            "connection",
            "upgrade",
            "sec-websocket-extensions",
            "host",
        ],
        vec![
            "sec-websocket-version",
            "sec-websocket-key",
            "connection",
            "upgrade",
            "sec-websocket-extensions",
            "host",
        ],
    ]
});

pub const STUPIDS: usize = 3;

pub const STUPID_NAMES: [&str; 45] = [
    "Prism", "Fusion", "Nexus", "Vortex", "Quasar",
    "Spectrum", "Photon", "Pulse", "Cipher", "Apex",
    "Zenith", "Echo", "Orbit", "Quantum", "Flux",
    "Nebula", "Halo", "Matrix", "Pyro", "Aurora",
    "Ember", "Glint", "Solstice", "Nova", "Dynamo",
    "Axis", "Blaze", "Mirage", "Titan", "Pylon",
    "Spark", "Tempest", "Haze", "Drift", "Starlight",
    "Inferno", "Galax", "Astra", "Vibe", "Element",
    "Cyclone", "Plasma", "Radiance", "Vivid", "Arc"
];

pub const BOT_NAMES: [&str; 576] = [
    "Æ⚡",
    "Ɠoblins",
    "ģŤǤ",
    "[MG]",
    "MƓR! ✌",
    "ØŠ",
    "ƤǤƒ",
    "Ɠoblins",
    "[Ek$!]",
    "ģŤǤ",
    "ŦŘǤŦ",
    "NaughtyCat(^.,.^)",
    "Killerkitty 2",
    "Darkitty (=^-^=)",
    "Mighty Snake",
    "BE CHILL",
    "LetMeLive",
    "I kill you",
    "1PROBLEM:UR LIVING",
    "Wigggly Worm",
    "Doğancan",
    "Šłïthèr",
    "🎨Anthorium",
    "-SlitheR-",
    "CAN YOU WIN?",
    "#$%ANTHORIUM🌺",
    "~_@_~",
    "☂",
    "lik dis if you are c00l",
    "Like dis if you got swag",
    "💀☠KILL😈YOU☠💀",
    "Türküz  amk bok nick sa",
    "♣♥♣AǤest♣♥♣",
    "___-COMER BOI_____-",
    "LUGUT",
    "☂",
    "☂",
    "VN:P",
    "margaret thatcha",
    "pin h 3",
    "Snapwingfriendstriker007",
    "everybodybecomespike",
    "a",
    "1",
    "vyde",
    "Mothership Drone",
    "op",
    "click F",
    "Noob",
    "🐰chiro🐰",
    "PJfd13",
    "CELESTIAL",
    "Team",
    "Pet :3",
    "FeZTiVAL",
    "anime",
    "t",
    "Rockety",
    "Valley",
    "Im New,dont kill me pls",
    "Friends?",
    "KILL ME I DARE YOU",
    "pet basic -(======>",
    "pet",
    "team ?",
    "Công",
    "Opan Come Go Note Yeah",
    "1 + 1 = 3",
    "Elite Knigh*",
    "vn{CHP}",
    "Dasher8162",
    "Xlo-250",
    "under_gamer092",
    "VN",
    "Mtp tv tiktoker",
    "Denied",
    "Paladin",
    "shame",
    "Corrupt Y",
    "spin= team",
    "Please no more Y team",
    "Syringe",
    "Pickerel Frog",
    "Bitter Dill",
    "Your Triggering Me 🤬",
    "117",
    "FleRex",
    "Archimedes",
    "Absolute Zero",
    "Frostbite Caves",
    "woohoo 1.982mil overlord",
    "[WTF] Comeme Soy Dulce",
    "Aniketos",
    "Lucas 1.51m",
    "Onomatopeja",
    "clqx",
    "big blue world",
    "ShinyShowers",
    "IM pro",
    "Juan+ ",
    "ee",
    "🌸🌸Patricia🌸🌸",
    "O",
    "Dywizjon   303",
    "{Insert Funny Name here}",
    "pancake",
    "XD",
    "arvaana",
    "lllaaaaaggggg",
    "- Awesome -",
    "xd",
    "leto",
    "noob 023 1mil surfur pog",
    "uwu uwu uwu uwu uwu uwu",
    "miao",
    "I Have Like you",
    "Bezmenov",
    "G+o+d=God   :)",
    "El Plasma Bomber",
    " (.o.) /",
    "B&G",
    "tiny lizard",
    "Peternos",
    "Chickens",
    "UraYla",
    "JD",
    "boo",
    "oli",
    "manco ]:",
    "C.H.K.N  T.N.D.R.S",
    "ENES",
    "🦠Bion Tech",
    "LORD",
    "a",
    "RedAlwaysSus",
    "2662636373727287272728$/",
    "Fire",
    "pls Don't kill",
    "Alien",
    "kubus",
    "++",
    "MONKE MAGIC",
    "[=>=)@NtHoNy=_==/=]%-%_%",
    "kevin",
    "E",
    "-",
    "qq",
    "unikit",
    "I'm new",
    "friends?",
    "square 100000000",
    "bot",
    "GUARDAESPALDAS",
    "Tyr",
    "1mil Mobile Smasher?",
    "ZII",
    "[LM]sinbadx",
    "X , 🎄🎇🎭 ",
    ";",
    "😈Tales",
    "im gonna ruin ur score",
    "uwu uwu uwu uwu uwu uwu",
    "Multi-shooter",
    "[VN]DCMTEAISGOOD",
    "[...] TIOP",
    "Pls dont kill me",
    "Dstroy",
    "🥺PIEN🥺",
    "OOOF",
    "vewe",
    "yes",
    "(;-; xin chào!!)",
    "K I D A",
    "SUS",
    "Pro ",
    " gustavo guardian2",
    "hello",
    "jojo xd",
    "clober",
    "Freedom or death",
    "Minh",
    "yeet",
    "dodo bird",
    "83",
    "lautaro ",
    "chào khánh",
    "Sos me",
    "💉 ",
    "Anastasios",
    "CHiM si cà bâu",
    "folontilô ._.",
    "pet",
    "Yo",
    " vn/ ne",
    ":(",
    "fff",
    "[VN] Vietnamese",
    "im new",
    "imagine 4v1 in 700k noob",
    "cc",
    "tank",
    "reeeeeeeeeeeeeeeeeeeeeee",
    "FALLEN SHOOTER",
    "bonnie",
    "HO",
    "tôi",
    "hai",
    "Sun",
    "snipe man",
    "U BA KA CHI",
    "D",
    "Somebody",
    "Scythe Faraday",
    "nark yt 45 ako",
    "The Beast",
    "  ",
    "AI LÀM NY TUI HONG ?",
    "🔥Destoryer🔥",
    "stinky",
    "Tanky",
    "ZadníStřítežCZ",
    "NO ONE MESSS WITH MEEEE.",
    "Carlos",
    "Klk",
    "roybot",
    "pls be my friend :D",
    "Sukhoi Su-30 Flanker(VN)",
    "bruhhhhhhh",
    "Mushy!",
    ".",
    "dont touch me or else",
    "+-Vex-+",
    "FPS dying please help",
    "amongus",
    "Huan",
    "switch 2 sprayer",
    "R Fusion",
    "Bork (Sweden)",
    "yo :)",
    "Ramza 😏",
    "isaax",
    "@_@",
    "min loras",
    " 2022",
    "cút ra ngoài",
    "drone branch = bad",
    "nonexistent",
    "The Dragon King",
    "<--- Is cool",
    "CjjcVv",
    "Pentium",
    "eesol",
    "Ace",
    "Incen",
    "BOOTER",
    "he",
    "yes",
    "GOALS TO WIN",
    "SOMEONE",
    "I",
    "jaffa calling",
    "Ill Tear your eyes out..",
    "Me-arac",
    "Aniketos",
    "🌌Miñe🌌",
    "Akilina",
    "Mythical",
    "exc",
    "=",
    "o o o o o o o o",
    "!!!",
    "Lixeiro do mal",
    "Thanks M8",
    "Frost? Mobile",
    "Dream",
    "We Do A Little Trolling",
    "earth",
    "NightFire",
    "Free to insult",
    "dino",
    "AMOGUS??????????????",
    "bruh",
    "",
    "No Surviors",
    "<[AXS]> RASHOT",
    "Pizza Bread",
    "[lag]Armando",
    "Overlord",
    "willim",
    "Everything RAM Mobile",
    "General",
    "{WOF} Nightwing",
    "footeloka",
    "Jes;/;ter",
    "Team Boom",
    "🖤ISAAC🖤",
    "naruto",
    "BigBadBoom",
    "nope",
    "glurip",
    "ffk the desrtroy",
    "Spin=Team",
    "comrade",
    "Alkali",
    "Impact of TY-77",
    "😈Stormys Domain😈",
    "YOUR BAD = YOUR DEAD!!!",
    "pushmetothe sancuary",
    "Im not a tank",
    "Snow",
    "Hm",
    "FOLLOW ME OCTO TANKS",
    "XP_Toxic_CJS",
    "TV",
    "constructor",
    "among us",
    "jkl",
    "XP_Toxic_CST",
    "d",
    "I love nahu",
    "Spade",
    "XxNicolas GamerxX",
    "xAd_rian",
    "FabianTu",
    "Eminx",
    "max",
    "OOOOOOOOFfffffffffffffff",
    "WalleeE",
    "MIKE",
    "pedro :(",
    "BEDROCK",
    "Hexagon Temple",
    "-_-",
    "You",
    "CACA",
    "Athena",
    "Artemis",
    "DOEBLE TOP!",
    "the only one",
    "hi (original)",
    "SOMEONE",
    "can you beat me smashey",
    "pika :P",
    "Fallen",
    "Big Papa",
    "GONIALS",
    "lnwZa007",
    "Daluns the one?",
    "CAMALEON",
    "factory not op :(",
    "/BIG BOYRockety",
    "circus of the dead",
    "hackercool",
    "Go Away",
    "Protector Of Worlds",
    "me",
    "vn",
    "RAHAN",
    "........................",
    "Soviet Union",
    "Flash",
    "🌌Miñe🌌",
    "King Pikachu",
    "EzzeKiel",
    "h",
    "Homeless man",
    "Asdfghjkjjhgfdsdfghjhgfd",
    "Felchas",
    "starwarrior",
    "Spin=Team",
    "Dream",
    "DIEGO",
    "Lagmat YT = 🎷 channel",
    "be dum like me",
    "lagg",
    "APplayer113",
    "tiky",
    "🇧🇷HUE🇧🇷",
    "am low, I Need Backup!",
    "Thunder(Tapenty)",
    "Beeg Yoshi Squad",
    "reeeeeeee",
    ";]",
    "Arena Closer",
    "abd lhalim",
    "Badaracco",
    "emir",
    "Türk  polisi",
    "Paladin",
    "stop plz",
    "d",
    "glenn <3 rachel",
    "[AI] Kidell",
    "dan",
    "I am milk",
    "Türk'ün Gücü Adına🌸 OwO",
    "Teuge",
    "Dave",
    "abbi_alin",
    "im a joke",
    "huy vn :D",
    "🌊🦈🌊",
    "scortt reach 1m friend",
    "ET",
    "vlasta",
    "Nyroca",
    "German",
    "I'm so lag(sinbadx)",
    "🇸🇦",
    "asdf",
    "Apollon",
    "^^",
    "I",
    "natasha",
    "no me mates amigos",
    "dáwsda",
    "FEWWW....",
    "lol",
    "A team with 💚 is doomed",
    "Raul39",
    "Noob AC",
    "ddqdqwdqw",
    "[MG] GLITCH TR",
    "LemonTea",
    "Party_CZE",
    "Diep_daodan",
    "What?",
    "kuro",
    "cute pet",
    "demon",
    "ALEXANDER👑💎",
    "Cursed",
    "copy The tank",
    "",
    "dsa.",
    "Vinh HD",
    "Mago",
    "hi UwU",
    "avn",
    "d",
    "naruto",
    "ARRASMONSTER KILLYOUha5x",
    "MICAH",
    "Jotaro",
    "king vn",
    "Raoof",
    "Leviathan",
    "SUN",
    "FALLEN SWORD",
    "🇧🇷HUE🇧🇷",
    "BoyFriend [FnF]",
    "motherhip",
    "lolera",
    "Dark Devil",
    "press F",
    "Detective Conan",
    "Pet",
    "MAICROFT",
    "Holy",
    "IXGAMËSS",
    "h",
    "umm,dab?",
    "Ihavelocty",
    "ewqasd2021vinicius",
    "[🇻🇳] Hùng",
    "I Love you",
    "Healer",
    "hacker lololololol",
    "boooster.io",
    "dscem",
    "bibi",
    "TEAM POLICE",
    "",
    "jj",
    "SHARK",
    "arena closer",
    "nani?",
    "OTTOMAN EMPİRE",
    "kr9ssy",
    "not P",
    "winnner",
    "friendly",
    "genocide BBB",
    "HI",
    "I'm poor:(fortnine duo",
    "JSABJSAB",
    "jmanplays",
    "starwarrior",
    "were",
    "PLAYER",
    "mothership protrector 1",
    "Gamer🎮",
    "6109",
    "PRO",
    "Opan Come Go Note Yeah",
    "Bowler",
    "ad",
    "haha bowler no 1M",
    "Tin",
    "[GZ]GESETA",
    "REVENGE✨",
    "Achi",
    "AC Perú",
    "bvnfgh",
    "hi",
    "Pet :3",
    "little",
    "khang",
    "lets be freinds guys!!!!",
    "sans pro",
    "phantanduy",
    "[AC] VGamerZ",
    "StevenUniverseFan",
    "azen",
    "Waffles",
    "jesian",
    "Overlord",
    "pikachuboi124",
    "mundo x bomb",
    "ducky",
    "🌀DESTROYER🌀",
    "Stupid Overlord",
    "++",
    "phantantri",
    "VoteOutRacists",
    "no",
    "Doofus",
    "MINI defender",
    "Alkaios",
    "I Love you",
    "fdsmn",
    "!",
    "R",
    "you shall not pass!!",
    "harmless shower",
    "lol",
    "oath sign",
    "finland",
    "bob",
    "VN~I LoVe You Chu Ca Mo",
    "Your mom",
    "Friendly",
    "the protector",
    "leave me alone pls",
    "Grill my flippen butt",
    "n o i c e",
    "bo",
    "onsen",
    "._.",
    "sinbadx",
    "Trackz",
    "D_D",
    "sussy BAKA",
    "Necrohacker",
    "🐺WOLFS🐺",
    "_[Necromancer]_",
    "Turk",
    "Wolf",
    "i am a noob lol",
    "kolibri",
    "OOF DIEE",
    "KİNG",
    "DOG",
    "Areixenoz",
    "S_me_ne",
    "Team",
    "Average-YT",
    "LEGEND X",
    "☂",
    "Shädam",
    "Aspekt",
    "Blaukanonkugel",
    "Schöpur",
    "Schteven",
    "Winfan8964",
    "Matheus Valaderas"
];